# auto execute scripts when xbmc starts, place this file in xbmchome\scripts\
#
# note: - do not execute more than one script at a time which asks for user input!
import sys, email, xbmcgui, xbmc, os
import time, mimetypes, re
import os.path, string
import glob, random

if(xbmc.Player().isPlayingAudio()):
	xbmc.Player().stop()

#xbmc.executebuiltin("xbmc.setvolume(50)")
	#time.sleep(0.1)
#xbmc.executescript('Q:\scripts\startupvideo-v0.1\startupvideo\default.py')

#while xbmc.Player().isPlayingVideo():
	#time.sleep(1)


#time.sleep(21)
#time.sleep(2)
#xbmc.executebuiltin("xbmc.setvolume(50)")

playlist = 	'Q:\\UserData\\playlists\\music\\1.m3u'
#playlist2 =	'Q:\\UserData\\playlists\\music\\1.xsp'
#playlist = 	'Q:\UserData\playlists\music\PC iTunes Lib 220708.m3u'
xbmc.executebuiltin("xbmc.SetVolume(30)")
xbmc.Player().play(playlist)
	
xbmc.executebuiltin("xbmc.SetVolume(31)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(32)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(33)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(34)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(35)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(36)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(37)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(38)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(39)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(40)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(41)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(42)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(43)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(44)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(45)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(46)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(47)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(48)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(49)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(50)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(51)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(52)")
time.sleep(0.1)
xbmc.executebuiltin("xbmc.SetVolume(53)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(54)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(55)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(56)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(57)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(58)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(59)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(60)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(61)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(62)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(63)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(64)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(65)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(66)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(67)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(68)")
time.sleep(0.2)
xbmc.executebuiltin("xbmc.SetVolume(69)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(70)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(71)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(72)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(73)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(74)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(75)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(76)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(77)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(78)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(79)")
time.sleep(0.3)
xbmc.executebuiltin("xbmc.SetVolume(80)")
time.sleep(0.4)
xbmc.executebuiltin("xbmc.SetVolume(81)")
time.sleep(0.4)
xbmc.executebuiltin("xbmc.SetVolume(82)")
time.sleep(0.4)
xbmc.executebuiltin("xbmc.SetVolume(83)")
time.sleep(0.5)
xbmc.executebuiltin("xbmc.SetVolume(84)")
time.sleep(0.5)
xbmc.executebuiltin("xbmc.SetVolume(85)")
time.sleep(0.6)
xbmc.executebuiltin("xbmc.SetVolume(86)")
time.sleep(0.7)
xbmc.executebuiltin("xbmc.SetVolume(87)")
time.sleep(0.8)
xbmc.executebuiltin("xbmc.SetVolume(88)")
time.sleep(0.9)
xbmc.executebuiltin("xbmc.SetVolume(89)")	
# comment	